### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by rri92366** [KcNirvana/MIUI-XML-12-PORTUGUESE#23]
![Screenshot_2020-11-11-12-52-47-568_com android settings](https://user-images.githubusercontent.com/74304485/98814241-4d08b580-241d-11eb-9145-5b5f23fa4d57.jpg)

**It doesn't say "monocelha" in Portuguese, I would like to help you translate.**

**Comment by KcNirvana** [comment]
> ![Screenshot_2020-11-11-12-52-47-568_com android settings](https://user-images.githubusercontent.com/74304485/98814241-4d08b580-241d-11eb-9145-5b5f23fa4d57.jpg)
> 
> **It doesn't say "monocelha" in Portuguese, I would like to help you translate.**

Boas...
Podemos falar em português.

Monocelha é o termo mais comum para designar o notch.
Tens alguma sugestão?

Abraço

**Comment by rri92366** [comment]
Boas,
O termo mais utilizado é entalhe.

Abraço

**Comment by rri92366** [comment]
Não está traduzido isto também.
![IMG_20201111_132804](https://user-images.githubusercontent.com/74304485/98817266-c5717580-2421-11eb-83c4-79a8474d086b.jpg)

**Comment by rri92366** [comment]
I use the version 20.11.5

**Comment by KcNirvana** [comment]
> Não está traduzido isto também.
> ![IMG_20201111_132804](https://user-images.githubusercontent.com/74304485/98817266-c5717580-2421-11eb-83c4-79a8474d086b.jpg)
> 

Está traduzido para a próxima release

**Comment by KcNirvana** [comment]
> I use the version 20.11.5

Podemos falar em tuga...
😁😁😁😁

**Comment by rri92366** [comment]
Esqueci-me 😅

**Comment by rri92366** [comment]
Gostava de ajudar, na tradução. De algumas cenas se precisarem
