### ISSUE TITLE
Tradução nas definições de bateria em falta

### ISSUE THREAD

**Issue by infusion92** [KcNirvana/MIUI-XML-12-PORTUGUESE#30]
Boas 

Antes de mais exelente trabalho que teem feito pela comunidade portuguesa

Existe algumas linhas nas definições de bateria que estão ainda em ingles :)
Caso encontre alguma coisa eu partilho

Cumprimentos

**Comment by KcNirvana** [comment]
Boas,
Podes mandar printscreens e dizer qual o dispositivo em questão?
Obrigado.


Abraço

**Comment by infusion92** [comment]
[Image]

[Image]


Mi9 SE
MIUI 12.5 Stable
Julgo já ter encontrado mais que estes dois mas são coisas mínimas, alguma coisa contacto novamente e deixo print

Obrigado, Abraço
________________________________
